### ISSUE TITLE
python

### ISSUE THREAD

**Issue by Crocks-jam** [Crocks-jam/crocks#1]
Let's pretend the spam includes the list ['a', 'b', 'c', 'd'] 
What is the value of spam[int(int('3' * 2) / 11)]?

**Comment by aynaamus** [comment]
int

**Comment by Andersoncorre** [comment]
A resposta é 3=d

**Comment by Andersoncorre** [comment]
resolução: primeiro o que esta dentro do parenteses ('3' * 2), por conta que o '3' é uma string e o 2 um numero inteiro, vai acabar resultando em '33' e no final sendo transformado em numero inteiro por conta do INT, o que acaba sendo divido por 11, resultando no final em 3, concluindo tudo no final fica: spam[3], concluindo tudo, mostra a chave numero 3, por tanto, 3=d.

**Comment by Uniquearjav** [comment]
the value of `spam[int(int('3' * 2) / 11)]` is `spam[3]`, which corresponds to the fourth element in the list since list indices start from 0. Therefore, the value would be 'd'.

**Comment by Crocks-jam** [comment]
Thank you so much guys for this solution.
